n = str(input('me fale seu nome: '))
nse = n.split()
espacos = n.count(' ')
tn = len(n)
pnl = len(nse[0])
print(f'seu nome com todas as letras maiúsculas ficaria: {n.upper()}')
print(f'seu nome com todas as letras minúsculas ficaria: {n.lower()}')
print(f'seu nome tem {tn - espacos} letras')
print(f'e seu primeiro nome tem {pnl} letras')
